# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
---
name: Build and test ingest_metadata

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run test suite
        run: |
          make test
          uv run codespell
          uv run yamllint -c .yamllint-config src/ingest_metadata/schema/ingest_metadata.yaml
