name: Validate-Ingest-Metadata-YAML

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    types: trigger-validate-ingest-metadata-yaml

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint -c .yamllint-config src/ingest_metadata/schema/ingest_metadata.yaml